apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
  # - image: pipenv_deps
  #   custom:
  #     buildCommand: tools/update_deps.sh
  - image: action_man
deploy:
  kubectl:
    manifests:
      - k8s/kafka/*.yaml
      - k8s/web/*.yaml
