"""001 bootstrap action

Revision ID: ad817b0e647b
Revises: 
Create Date: 2020-03-05 15:47:03.922161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad817b0e647b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('experiment_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('variant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_experiment_id'), 'action', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_action_variant_id'), 'action', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_variant_id'), table_name='action')
    op.drop_index(op.f('ix_action_experiment_id'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
